use std::{
    collections::HashMap,
    path::{Path, PathBuf},
    sync::{Mutex, OnceLock},
};

pub use error::ExportError;
pub(crate) use recursive_export::export_all_into;

use crate::{Config, TS};

mod doc;
mod error;
mod format;
mod path;

static EXPORT_PATHS: OnceLock<Mutex<HashMap<PathBuf, Vec<Entry>>>> = OnceLock::new();

fn get_export_paths<'a>() -> &'a Mutex<HashMap<PathBuf, Vec<Entry>>> {
    EXPORT_PATHS.get_or_init(Default::default)
}

const NOTE: &str = "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n";

mod recursive_export {
    use std::{any::TypeId, collections::HashSet};

    use super::export_into;
    use crate::{Config, ExportError, TypeVisitor, TS};

    /// Exports `T` to the file specified by the `#[ts(export_to = ..)]` attribute within the given
    /// base directory.  
    /// Additionally, all dependencies of `T` will be exported as well.
    pub(crate) fn export_all_into<T: TS + ?Sized + 'static>(
        cfg: &Config,
    ) -> Result<(), ExportError> {
        let mut seen = HashSet::new();
        export_recursive::<T>(cfg, &mut seen)
    }

    struct Visit<'a> {
        cfg: &'a Config,
        seen: &'a mut HashSet<TypeId>,
        error: Option<ExportError>,
    }

    impl TypeVisitor for Visit<'_> {
        fn visit<T: TS + 'static + ?Sized>(&mut self) {
            // if an error occurred previously, or the type cannot be exported (it's a primitive),
            // we return
            if self.error.is_some() || <T as crate::TS>::output_path().is_none() {
                return;
            }

            self.error = export_recursive::<T>(self.cfg, self.seen).err();
        }
    }

    // exports T, then recursively calls itself with all of its dependencies
    fn export_recursive<T: TS + ?Sized + 'static>(
        cfg: &Config,
        seen: &mut HashSet<TypeId>,
    ) -> Result<(), ExportError> {
        if !seen.insert(TypeId::of::<T>()) {
            return Ok(());
        }

        export_into::<T>(cfg)?;

        let mut visitor = Visit {
            cfg,
            seen,
            error: None,
        };
        <T as crate::TS>::visit_dependencies(&mut visitor);

        if let Some(e) = visitor.error {
            Err(e)
        } else {
            Ok(())
        }
    }
}

/// Export `T` to the file specified by the `#[ts(export_to = ..)]` attribute
pub(crate) fn export_into<T: TS + ?Sized + 'static>(cfg: &Config) -> Result<(), ExportError> {
    let path = <T as crate::TS>::output_path()
        .ok_or_else(std::any::type_name::<T>)
        .map_err(ExportError::CannotBeExported)?;
    let path = cfg.export_dir.join(path);

    export_to::<T, _>(cfg, path::absolute(path)?)
}

/// Export `T` to the file specified by the `path` argument.
pub(crate) fn export_to<T: TS + ?Sized + 'static, P: AsRef<Path>>(
    cfg: &Config,
    path: P,
) -> Result<(), ExportError> {
    let path = path.as_ref().to_owned();

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    export_and_merge(path, Entry::new(&generate_decl::<T>(cfg)))
}

/// A declaration written to an export file: parsed, so it prints exactly as
/// `rescript format` would, or kept as generated when it uses syntax the
/// formatter doesn't know.
enum Entry {
    Parsed(format::Decl),
    Raw { name: String, text: String },
}

impl Entry {
    fn new(generated: &str) -> Self {
        match format::parse(generated) {
            Some(mut decls) if decls.len() == 1 => Entry::Parsed(decls.pop().unwrap()),
            _ => Entry::Raw {
                name: raw_name(generated),
                text: generated.trim_matches('\n').to_owned(),
            },
        }
    }

    fn name(&self) -> &str {
        match self {
            Entry::Parsed(decl) => &decl.name,
            Entry::Raw { name, .. } => name,
        }
    }
}

fn raw_name(decl: &str) -> String {
    decl.split("type ")
        .last()
        .and_then(|rest| rest.split(|c: char| c.is_whitespace() || c == '<').next())
        .unwrap_or_default()
        .to_owned()
}

/// Adds the declaration to the file's declarations, kept sorted by name, and
/// rewrites the file. The first export to a path in this process starts the
/// file afresh.
fn export_and_merge(path: PathBuf, entry: Entry) -> Result<(), ExportError> {
    let lock = &mut get_export_paths().lock().unwrap();
    let entries = lock.entry(path.clone()).or_default();

    match entries.binary_search_by(|e| e.name().cmp(entry.name())) {
        Ok(_) => return Ok(()),
        Err(at) => entries.insert(at, entry),
    }

    std::fs::write(&path, render(entries))?;

    Ok(())
}

fn render(entries: &[Entry]) -> String {
    let parsed: Vec<_> = entries
        .iter()
        .filter_map(|e| match e {
            Entry::Parsed(decl) => Some(decl),
            Entry::Raw { .. } => None,
        })
        .collect();

    let body = if parsed.len() == entries.len() {
        format::print(&parsed)
    } else {
        let texts: Vec<_> = entries
            .iter()
            .map(|e| match e {
                Entry::Parsed(decl) => format::print(&[decl]),
                Entry::Raw { text, .. } => text.clone(),
            })
            .collect();
        make_mutually_recursive(&texts.join("\n\n"))
    };

    format!("{NOTE}\n{body}\n")
}

/// When a file contains multiple type declarations, convert them to
/// `type rec ... and ...` so that types can reference each other
/// regardless of declaration order.
fn make_mutually_recursive(declarations: &str) -> String {
    let type_count = declarations
        .lines()
        .filter(|line| line.starts_with("type "))
        .count();

    if type_count <= 1 {
        return declarations.to_owned();
    }

    let mut result = String::with_capacity(declarations.len() + 4);
    let mut is_first = true;

    for line in declarations.lines() {
        if !result.is_empty() {
            result.push('\n');
        }

        if line.starts_with("type ") {
            if is_first {
                result.push_str("type rec ");
                result.push_str(&line["type ".len()..]);
                is_first = false;
            } else {
                result.push_str("and ");
                result.push_str(&line["type ".len()..]);
            }
        } else {
            result.push_str(line);
        }
    }

    result
}

/// Returns the generated definition for `T`.
pub(crate) fn export_to_string<T: TS + ?Sized + 'static>(
    cfg: &Config,
) -> Result<String, ExportError> {
    Ok(render(&[Entry::new(&generate_decl::<T>(cfg))]))
}

/// The declaration of `T`, with its doc comment.
fn generate_decl<T: TS + ?Sized>(cfg: &Config) -> String {
    let mut out = <T as crate::TS>::docs().unwrap_or_default();
    out.push_str(&<T as crate::TS>::decl(cfg));
    out
}
