#![allow(dead_code)]

use std::{concat, fs};

use rescript_rs::{Config, TS};
#[cfg(feature = "serde-compat")]
use serde::Serialize;

/// Doc comment.
/// Supports new lines.
///
/// Testing
#[derive(TS)]
#[rescript(export_to = "docs/")]
struct A {
    /// Doc of field
    ///
    /// Testing
    name: String,
}

#[derive(TS)]
#[rescript(export_to = "docs/")]
/// Doc comment.
/// Supports new lines.
///
/// Testing
struct B {
    /// Doc of field
    ///
    /// Testing
    name: String,
}

#[derive(TS)]
#[rescript(export_to = "docs/")]
/// Doc comment.
/// Supports new lines.
///
/// Testing
struct C {}

#[derive(TS)]
#[rescript(export_to = "docs/")]
/// Doc comment.
/// Supports new lines.
///
/// Testing
struct D;

#[derive(TS)]
#[rescript(export_to = "docs/")]
/// Doc comment.
/// Supports new lines.
///
/// Testing
enum E {}

#[derive(TS)]
#[cfg_attr(feature = "serde-compat", derive(Serialize))]
#[cfg_attr(feature = "serde-compat", serde(tag = "type", content = "value"))]
#[cfg_attr(
    not(feature = "serde-compat"),
    rescript(tag = "type", content = "value")
)]
#[rescript(export_to = "docs/")]
/// Doc comment.
/// Supports new lines.
///
/// Testing
enum F {
    /// Doc of variant
    ///
    /// Testing
    VarA,
    /// Doc of variant
    ///
    /// Testing
    VarB(),
    /// Doc of variant
    ///
    /// Testing
    VarC {
        /// Doc of field of variant
        ///
        /// Testing
        variant_field: i32,
    },
}

#[derive(TS)]
#[rescript(export_to = "docs/")]
struct G {
    /// Docs
    some_other_field: i32,

    /// Some documentation that should probably NOT be exported
    #[rescript(flatten)]
    f: F,
}

#[derive(TS)]
#[rescript(export_to = "docs/")]
/**
 * Block doc comment
 *
 * works
 */
struct H {
    foo: i32,
}

#[derive(TS)]
#[rescript(export_to = "docs/")]
#[doc = concat!("line ", line!())]
struct I {
    #[doc = concat!("column ", column!())]
    a: i32,

    #[doc = concat!("path ", module_path!())]
    b: i32,
}

#[test]
fn export_a() {
    let cfg = Config::from_env();
    A::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "/**\n",
        " * Doc comment.\n",
        " * Supports new lines.\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "type a = {\n",
        "  /**\n",
        " * Doc of field\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "  name: string,\n",
        "}\n",
    );

    let actual_content = super::read_file::<A>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_b() {
    let cfg = Config::from_env();
    B::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "/**\n",
        " * Doc comment.\n",
        " * Supports new lines.\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "type b = {\n",
        "  /**\n",
        " * Doc of field\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "  name: string,\n",
        "}\n",
    );

    let actual_content = super::read_file::<B>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_c() {
    let cfg = Config::from_env();
    C::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "/**\n",
        " * Doc comment.\n",
        " * Supports new lines.\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "type c = {}\n",
    );

    let actual_content = super::read_file::<C>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_d() {
    let cfg = Config::from_env();
    D::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "/**\n",
        " * Doc comment.\n",
        " * Supports new lines.\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "type d = unit\n",
    );

    let actual_content = super::read_file::<D>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_e() {
    let cfg = Config::from_env();
    E::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "/**\n",
        " * Doc comment.\n",
        " * Supports new lines.\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "type e = never\n",
    );

    let actual_content = super::read_file::<E>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_f() {
    let cfg = Config::from_env();
    F::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "/**\n",
        " * Doc comment.\n",
        " * Supports new lines.\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "@tag(\"type\")\n",
        "type f = \n  | VarA\n  | VarB({ value: array<never> })\n  | VarC({ value: { \n",
        "/**\n",
        " * Doc of field of variant\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "variant_field: int, } })\n",
    );

    let actual_content = super::read_file::<F>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_g() {
    let cfg = Config::from_env();
    G::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "type g = { \n",
        "/**\n",
        " * Docs\n",
        " */\n",
        "some_other_field: int, } & (| VarA | VarB({ value: array<never> }) | VarC({ value: { \n",
        "/**\n",
        " * Doc of field of variant\n",
        " *\n",
        " * Testing\n",
        " */\n",
        "variant_field: int, } }))\n",
    );

    let actual_content = super::read_file::<G>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_h() {
    let cfg = Config::from_env();
    H::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "/**\n",
        " * Block doc comment\n",
        " *\n",
        " * works\n",
        " */\n",
        "type h = {\n  foo: int,\n}\n",
    );

    let actual_content = super::read_file::<H>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_i() {
    let cfg = Config::from_env();
    I::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n\n",
        "/**\n",
        " *line 115\n",
        " */\n",
        "type i = {\n",
        "  /**\n",
        " *column 32\n",
        " */\n",
        "  a: int,\n",
        "  /**\n",
        " *path integration::docs\n",
        " */\n",
        "  b: int,\n",
        "}\n",
    );

    let actual_content = super::read_file::<I>(&cfg);
    assert_eq!(actual_content, expected_content);
}
